name: Validate Dataset

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r scripts/requirements.txt

      - name: Validate XML and count facts
        run: |
          python scripts/validate.py | tee -a $GITHUB_STEP_SUMMARY
